version: 0.2
phases:
  install:
    commands:
      - echo "Install Phase - if you need additional package, add it in this stage"
  pre_build:
      commands:
        - aws --version
        # Login to ECR Registry 
        - echo "Login in to Amazon ECR Registry"
        - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 010928179293.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      # Building Docker Image
      - echo "Docker build started on `date`"
      - echo "Building the Docker image..."
      - TAG="nodeJS-$(date +%Y-%m-%d.%H.%M.%S)"
      - docker build --tag 010928179293.dkr.ecr.us-east-1.amazonaws.com/test:${TAG} .
  post_build:
    commands:
      # Push Docker Image to ECR Repository
      - echo "Docker build completed on `date`"
      - echo "Pushing the Docker image to ECR Repository"
      - docker push 010928179293.dkr.ecr.us-east-1.amazonaws.com/test:${TAG}
      - echo "Docker Push to ECR Repository Completed -  $REPOSITORY_URI:$TAG"
      - sed -i "s|\${IMAGE_URL}|${TAG}|g" node_deploy.yaml
      - cat node_deploy.yaml
artifacts:
  files:
    - "**/*"
  base-directory: /home/ubuntu/deployments