apiVersion: v1
kind: Service
metadata:
  name: nodejs-svc
spec:
  selector:
    app: nodejs
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30080  # Specify the nodePort
  type: NodePort