apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: Image
        name: nodejs
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: ecr-registry-secret